services:
  - type: web
    name: pii-masking-backend
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y python3 python3-pip tesseract-ocr poppler-utils
      npm install
      pip3 install pytesseract pillow spacy pdf2image python-docx
      python3 -m spacy download en_core_web_sm
    startCommand: node server.js
    envVars:
      - key: ENCRYPTION_KEY
        value: ad7f8d9c3b93f9271a4f28a6f76e5e873f0932ad9f23b5c87d6f27ad7e9fbc64
      - key: IV
        value: 52a1c82e3f9d5f8c7a3b2c1d6e4f9a71
      - key: JWT_SECRET
        value: d8d6d6ef6c7a8d56ab8c6e6f27f3d7b14c9a8b6f5b7a8c2b9d6e6b3a8c9d3e6a
